'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'es' | 'hi' | 'ar' | 'vi';

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRtl: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.categories': 'Categories',
    'nav.exportCountries': 'Export Destinations',
    'nav.quality': 'Quality',
    'nav.plant': 'Processing Plant',
    'nav.certifications': 'Certifications',
    'nav.calculator': 'Container Calculator',
    'nav.about': 'About Us',
    'nav.contact': 'Contact Us',
    'nav.buyerDashboard': 'Buyer Dashboard',
    'nav.adminDashboard': 'Admin Panel',
    'hero.title': "Exporting India's Finest Chillies Worldwide",
    'hero.subtitle': 'Premium Indian Chillies Exporter & Supplier',
    'hero.cta': 'Get Instant Quote',
    'hero.badge1': '100+ Products',
    'hero.badge2': '50+ Countries Sourced',
    'hero.badge3': 'ISO & HACCP Certified',
    'stats.containers': 'Containers Exported',
    'stats.countries': 'Countries Served',
    'stats.buyers': 'Satisfied Buyers',
    'stats.satisfaction': 'Quality Rating',
    'rfq.title': 'Submit Bulk B2B Inquiry',
    'rfq.subtitle': 'Receive a custom FOB/CIF quote within 12 hours from our team',
    'rfq.name': 'Your Name',
    'rfq.company': 'Company Name',
    'rfq.country': 'Destination Country',
    'rfq.email': 'Business Email',
    'rfq.phone': 'Phone / WhatsApp',
    'rfq.product': 'Select Chilli Variety',
    'rfq.quantity': 'Quantity (Metric Tons)',
    'rfq.packaging': 'Preferred Packaging',
    'rfq.port': 'Destination Port',
    'rfq.message': 'Special Specifications / Requirements',
    'rfq.submit': 'Request Quote Now',
    'footer.rights': 'All Rights Reserved. ABHI GLOBAL EXPORTS.',
    'footer.desc': 'Leading processor and international exporter of high-grade Indian red chillies, chilli powders, flakes, and seeds directly from Guntur farms.',
    'common.moq': 'MOQ',
    'common.heat': 'Heat Level',
    'common.shu': 'SHU (Heat)',
    'common.asta': 'ASTA (Color)',
    'common.origin': 'Origin',
    'common.price': 'Price',
    'common.inquire': 'Request Price',
    'common.compare': 'Compare',
    'common.details': 'View Details',
    'common.organic': 'Organic Sourced',
    'common.cleaned': 'Machine Cleaned',
    'chatbot.welcome': 'Welcome to ABHI GLOBAL EXPORTS AI Assistant. Ask me about our chillies, heat levels, certifications, shipping capacities, or request a quote!',
    'chatbot.placeholder': 'Type your question...',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.products': 'Productos',
    'nav.categories': 'Categorías',
    'nav.exportCountries': 'Destinos de Exportación',
    'nav.quality': 'Calidad',
    'nav.plant': 'Planta de Procesamiento',
    'nav.certifications': 'Certificaciones',
    'nav.calculator': 'Calculadora de Contenedores',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.buyerDashboard': 'Panel del Comprador',
    'nav.adminDashboard': 'Panel de Administración',
    'hero.title': 'Exportando los mejores chiles de la India al mundo',
    'hero.subtitle': 'Exportador y proveedor premium de chiles de la India',
    'hero.cta': 'Obtenga cotización instantánea',
    'hero.badge1': '100+ Productos',
    'hero.badge2': '50+ Países',
    'hero.badge3': 'Certificación ISO y HACCP',
    'stats.containers': 'Contenedores Exportados',
    'stats.countries': 'Países Atendidos',
    'stats.buyers': 'Compradores Satisfechos',
    'stats.satisfaction': 'Calificación de Calidad',
    'rfq.title': 'Enviar solicitud B2B al por mayor',
    'rfq.subtitle': 'Reciba una cotización personalizada FOB/CIF en menos de 12 horas',
    'rfq.name': 'Su Nombre',
    'rfq.company': 'Nombre de la Empresa',
    'rfq.country': 'País de Destino',
    'rfq.email': 'Correo Comercial',
    'rfq.phone': 'Teléfono / WhatsApp',
    'rfq.product': 'Seleccione variedad de chile',
    'rfq.quantity': 'Cantidad (Toneladas Métricas)',
    'rfq.packaging': 'Embalaje Preferido',
    'rfq.port': 'Puerto de Destino',
    'rfq.message': 'Especificaciones / Requisitos especiales',
    'rfq.submit': 'Solicitar Cotización Ahora',
    'footer.rights': 'Todos los derechos reservados. ABHI GLOBAL EXPORTS.',
    'footer.desc': 'Procesador líder y exportador internacional de chiles rojos indios de alta calidad, chiles en polvo, hojuelas y semillas directamente desde las granjas de Guntur.',
    'common.moq': 'MOQ (Pedido Mín)',
    'common.heat': 'Nivel de Picante',
    'common.shu': 'SHU (Picante)',
    'common.asta': 'ASTA (Color)',
    'common.origin': 'Origen',
    'common.price': 'Precio',
    'common.inquire': 'Solicitar Precio',
    'common.compare': 'Comparar',
    'common.details': 'Ver Detalles',
    'common.organic': 'Origen Orgánico',
    'common.cleaned': 'Limpiado a Máquina',
    'chatbot.welcome': 'Bienvenido al Asistente de IA de ABHI GLOBAL EXPORTS. ¡Pregúnteme sobre nuestros chiles, niveles de picante, certificaciones o solicite una cotización!',
    'chatbot.placeholder': 'Escriba su pregunta...',
  },
  hi: {
    'nav.home': 'होम',
    'nav.products': 'उत्पाद',
    'nav.categories': 'श्रेणियां',
    'nav.exportCountries': 'निर्यात देश',
    'nav.quality': 'गुणवत्ता',
    'nav.plant': 'प्रोसेसिंग प्लांट',
    'nav.certifications': 'प्रमाणपत्र',
    'nav.calculator': 'कंटेनर कैलकुलेटर',
    'nav.about': 'हमारे बारे में',
    'nav.contact': 'संपर्क करें',
    'nav.buyerDashboard': 'बायर्स डैशबोर्ड',
    'nav.adminDashboard': 'एडमिन पैनल',
    'hero.title': 'भारत की सर्वश्रेष्ठ लाल मिर्च का वैश्विक निर्यात',
    'hero.subtitle': 'प्रीमियम भारतीय मिर्च निर्यातक एवं आपूर्तिकर्ता',
    'hero.cta': 'त्वरित उद्धरण प्राप्त करें',
    'hero.badge1': '100+ उत्पाद',
    'hero.badge2': '50+ देश',
    'hero.badge3': 'ISO और HACCP प्रमाणित',
    'stats.containers': 'निर्यातित कंटेनर',
    'stats.countries': 'सेवाकृत देश',
    'stats.buyers': 'संतुष्ट खरीदार',
    'stats.satisfaction': 'गुणवत्ता रेटिंग',
    'rfq.title': 'थोक B2B पूछताछ भेजें',
    'rfq.subtitle': 'हमारी टीम से 12 घंटे के भीतर कस्टम FOB/CIF उद्धरण प्राप्त करें',
    'rfq.name': 'आपका नाम',
    'rfq.company': 'कंपनी का नाम',
    'rfq.country': 'गंतव्य देश',
    'rfq.email': 'व्यावसायिक ईमेल',
    'rfq.phone': 'फ़ोन / व्हाट्सएप',
    'rfq.product': 'मिर्च की विविधता चुनें',
    'rfq.quantity': 'मात्रा (मीट्रिक टन)',
    'rfq.packaging': 'पसंदीदा पैकेजिंग',
    'rfq.port': 'गंतव्य बंदरगाह',
    'rfq.message': 'विशेष विवरण / आवश्यकताएं',
    'rfq.submit': 'अभी पूछताछ करें',
    'footer.rights': 'सर्वाधिकार सुरक्षित। ABHI GLOBAL EXPORTS.',
    'footer.desc': 'गुंटूर के खेतों से सीधे उच्च गुणवत्ता वाली भारतीय लाल मिर्च, मिर्च पाउडर, फ्लेक्स और बीजों के अग्रणी प्रसंस्करणकर्ता और अंतरराष्ट्रीय निर्यातक।',
    'common.moq': 'MOQ (न्यूनतम ऑर्डर)',
    'common.heat': 'तीखापन स्तर',
    'common.shu': 'SHU (तीखापन)',
    'common.asta': 'ASTA (रंग)',
    'common.origin': 'उत्पत्ति',
    'common.price': 'कीमत',
    'common.inquire': 'कीमत का अनुरोध करें',
    'common.compare': 'तुलना करें',
    'common.details': 'विवरण देखें',
    'common.organic': 'जैविक स्रोत',
    'common.cleaned': 'मशीन से साफ',
    'chatbot.welcome': 'अभि ग्लोबल एक्सपोर्ट्स एआई असिस्टेंट में आपका स्वागत है। हमसे हमारी मिर्च, तीखापन स्तर, प्रमाणपत्र, शिपिंग क्षमता के बारे में पूछें!',
    'chatbot.placeholder': 'अपना प्रश्न टाइप करें...',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.products': 'المنتجات',
    'nav.categories': 'الفئات',
    'nav.exportCountries': 'وجهات التصدير',
    'nav.quality': 'الجودة',
    'nav.plant': 'مصنع المعالجة',
    'nav.certifications': 'الشهادات',
    'nav.calculator': 'حاسبة الحاويات',
    'nav.about': 'من نحن',
    'nav.contact': 'اتصل بنا',
    'nav.buyerDashboard': 'لوحة المشتري',
    'nav.adminDashboard': 'لوحة التحكم',
    'hero.title': 'تصدير أفضل أنواع الفلفل الأحمر الهندي لجميع أنحاء العالم',
    'hero.subtitle': 'مصدّر ومورّد متميز للفلفل الهندي الفاخر',
    'hero.cta': 'احصل على تسعيرة فورية',
    'hero.badge1': 'أكثر من 100 منتج',
    'hero.badge2': 'أكثر من 50 دولة',
    'hero.badge3': 'شهادات الأيزو والهاسب',
    'stats.containers': 'حاويات تم تصديرها',
    'stats.countries': 'بلدان نخدمها',
    'stats.buyers': 'مشترون راضون',
    'stats.satisfaction': 'تقييم الجودة',
    'rfq.title': 'ارسل طلب استفسار بالجملة B2B',
    'rfq.subtitle': 'احصل على عرض سعر مخصص FOB / CIF خلال 12 ساعة من فريقنا',
    'rfq.name': 'اسمك الكامل',
    'rfq.company': 'اسم الشركة',
    'rfq.country': 'بلد الوجهة',
    'rfq.email': 'البريد الإلكتروني للعمل',
    'rfq.phone': 'الهاتف / الواتساب',
    'rfq.product': 'اختر نوع الفلفل',
    'rfq.quantity': 'الكمية (بالأطنان المترية)',
    'rfq.packaging': 'التعبئة والتغليف المفضل',
    'rfq.port': 'ميناء الوجهة',
    'rfq.message': 'المواصفات الخاصة / المتطلبات',
    'rfq.submit': 'اطلب عرض سعر الآن',
    'footer.rights': 'جميع الحقوق محفوظة. ABHI GLOBAL EXPORTS.',
    'footer.desc': 'المعالج الرائد والمصدر الدولي للفلفل الأحمر الهندي الفاخر، مساحيق الفلفل، والرقائق، والبذور مباشرة من مزارع غونتور.',
    'common.moq': 'الحد الأدنى للطلب',
    'common.heat': 'مستوى الحرارة',
    'common.shu': 'SHU (الحرارة)',
    'common.asta': 'ASTA (اللون)',
    'common.origin': 'المنشأ',
    'common.price': 'السعر',
    'common.inquire': 'طلب السعر',
    'common.compare': 'مقارنة',
    'common.details': 'عرض التفاصيل',
    'common.organic': 'عضوي المصدر',
    'common.cleaned': 'منظف آلياً',
    'chatbot.welcome': 'مرحبًا بك في المساعد الذكي لشركة ABHI GLOBAL EXPORTS. اسألني عن الفلفل ومستويات الحرارة أو الشحن والشهادات!',
    'chatbot.placeholder': 'اكتب سؤالك هنا...',
  },
  vi: {
    'nav.home': 'Trang chủ',
    'nav.products': 'Sản phẩm',
    'nav.categories': 'Danh mục',
    'nav.exportCountries': 'Điểm đến Xuất khẩu',
    'nav.quality': 'Chất lượng',
    'nav.plant': 'Nhà máy chế biến',
    'nav.certifications': 'Chứng nhận',
    'nav.calculator': 'Tính toán Container',
    'nav.about': 'Giới thiệu',
    'nav.contact': 'Liên hệ',
    'nav.buyerDashboard': 'Trang người mua',
    'nav.adminDashboard': 'Trang quản trị',
    'hero.title': 'Xuất khẩu ớt đỏ tốt nhất của Ấn Độ trên toàn thế giới',
    'hero.subtitle': 'Nhà xuất khẩu & Cung cấp ớt Ấn Độ cao cấp',
    'hero.cta': 'Nhận báo giá ngay',
    'hero.badge1': '100+ Sản phẩm',
    'hero.badge2': '50+ Quốc gia',
    'hero.badge3': 'Chứng nhận ISO & HACCP',
    'stats.containers': 'Container đã xuất khẩu',
    'stats.countries': 'Quốc gia phục vụ',
    'stats.buyers': 'Khách hàng hài lòng',
    'stats.satisfaction': 'Đánh giá chất lượng',
    'rfq.title': 'Gửi yêu cầu báo giá B2B số lượng lớn',
    'rfq.subtitle': 'Nhận báo giá FOB/CIF tùy chỉnh trong vòng 12 giờ từ đội ngũ của chúng tôi',
    'rfq.name': 'Tên của bạn',
    'rfq.company': 'Tên công ty',
    'rfq.country': 'Quốc gia đích',
    'rfq.email': 'Email doanh nghiệp',
    'rfq.phone': 'Số điện thoại / WhatsApp',
    'rfq.product': 'Chọn loại ớt',
    'rfq.quantity': 'Số lượng (Tấn)',
    'rfq.packaging': 'Quy cách đóng gói',
    'rfq.port': 'Cảng đến',
    'rfq.message': 'Yêu cầu & Thông số kỹ thuật đặc biệt',
    'rfq.submit': 'Yêu cầu báo giá ngay',
    'footer.rights': 'Bản quyền thuộc về ABHI GLOBAL EXPORTS.',
    'footer.desc': 'Nhà chế biến và xuất khẩu quốc tế hàng đầu về ớt đỏ Ấn Độ chất lượng cao, bột ớt, ớt lát và hạt trực tiếp từ trang trại Guntur.',
    'common.moq': 'MOQ',
    'common.heat': 'Mức độ cay',
    'common.shu': 'SHU (Cay)',
    'common.asta': 'ASTA (Màu sắc)',
    'common.origin': 'Nguồn gốc',
    'common.price': 'Giá cả',
    'common.inquire': 'Yêu cầu báo giá',
    'common.compare': 'So sánh',
    'common.details': 'Chi tiết',
    'common.organic': 'Nguồn gốc hữu cơ',
    'common.cleaned': 'Làm sạch bằng máy',
    'chatbot.welcome': 'Chào mừng đến với Trợ lý AI của ABHI GLOBAL EXPORTS. Hãy hỏi tôi về các loại ớt, độ cay, chứng nhận hoặc yêu cầu báo giá!',
    'chatbot.placeholder': 'Nhập câu hỏi của bạn...',
  }
};

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  // Load language from localStorage if client side
  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved && translations[saved]) {
      setLanguage(saved);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  const isRtl = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, isRtl }}>
      <div dir={isRtl ? 'rtl' : 'ltr'}>{children}</div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
